volumes:
  memberme:
    external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      NODE_ENV: development
      HOST: "0.0.0.0"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_SERVICE: ${REACT_APP_SERVICE}
      DATABASE_URL: ${DATABASE_URL}
      WAIT_HOSTS: db:5432
      PORT: 8000
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  db:
    build:
      context: relational-data
      dockerfile: Dockerfile.dev
    volumes:
      - memberme:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: memberme
      POSTGRES_USER: memberme
      POSTGRES_DB: memberme
    ports:
      - "15432:5432"
