# Generated by Django 4.0.3 on 2022-11-03 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sales_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="sales_rest.employeevo",
            ),
        ),
    ]
