# Generated by Django 4.0.3 on 2022-11-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_rest', '0002_position_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
