# Generated by Django 4.0.3 on 2022-10-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomobileVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_href",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("color", models.CharField(max_length=50)),
                ("year", models.PositiveSmallIntegerField()),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("model_id", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_name", models.CharField(max_length=100)),
                ("employee_number", models.PositiveSmallIntegerField(unique=True)),  # noqa: E501
            ],
        ),
        migrations.CreateModel(
            name="ServiceAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=100)),
                ("appointment_date", models.DateTimeField()),
                ("reason", models.CharField(max_length=300)),
                ("status", models.CharField(default="scheduled", max_length=25)),  # noqa: E501
                (
                    "automobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="service_rest.automobilevo",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="service_rest.technician",
                    ),
                ),
            ],
        ),
    ]
