# Generated by Django 4.0.3 on 2022-11-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_rename_tech_name_technician_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceAppointment',
            new_name='Service',
        ),
    ]
