# Generated by Django 4.0.3 on 2022-11-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_rename_serviceappointment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='owner_name',
            new_name='customer_name',
        ),
    ]
