# Generated by Django 4.0.3 on 2022-11-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0005_rename_owner_name_service_customer_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="customer_name",
            new_name="customer",
        ),
    ]
