# Generated by Django 4.0.3 on 2022-11-03 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0007_employeevo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="service_rest.employeevo",
            ),
        ),
        migrations.DeleteModel(
            name="Technician",
        ),
    ]
