# Generated by Django 4.0.3 on 2022-11-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0008_alter_service_technician_delete_technician"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_href",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone_number", models.PositiveBigIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="service_rest.customervo",
            ),
        ),
    ]
